### ISSUE TITLE
Not work with bitnami_redmine-3.2.0-0.

### ISSUE THREAD

**Issue by walkwolf** [Loriowar/redmine_issues_tree#20]
Install bitnami_redmine-3.2.0-0
cd $install_home/redmine-3.2.0-0/
./use_redmine 
cd $install_home/redmine-3.2.0-0/apps/redmine/htdocs/plugins
git clone https://github.com/Loriowar/redmine_issues_tree.git
gem install require_patch -v 0.1.0
gem install haml-rails
rake redmine:plugins:migrate RAILS_ENV=production

Then I got
```
RedmineApp::Application.load_tasks
bash-4.1$ rake redmine:plugins:migrate RAILS_ENV=production
rake aborted!
NoMethodError: undefined method `require_patch' for #<ActionDispatch::Reloader:0x007f7bed19d6e0>
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/plugins/redmine_issues_tree/init.rb:15:in `block in <top (required)>'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:446:in `instance_exec'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:446:in `block in make_lambda'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:192:in `call'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:192:in `block in simple'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:504:in `call'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:504:in `block in call'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:504:in `each'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:504:in `call'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:778:in `_run_prepare_callbacks'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:81:in `run_callbacks'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/reloader.rb:55:in `prepare!'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/railties-4.2.5/lib/rails/application/finisher.rb:50:in `block in <module:Finisher>'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `instance_exec'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `run'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/railties-4.2.5/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/railties-4.2.5/lib/rails/initializable.rb:54:in `run_initializers'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/railties-4.2.5/lib/rails/application.rb:352:in `initialize!'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/config/environment.rb:14:in `<top (required)>'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/railties-4.2.5/lib/rails/application.rb:328:in `require_environment!'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/railties-4.2.5/lib/rails/application.rb:457:in `block in run_tasks_blocks'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```

**Comment by Loriowar** [comment]
First of all: which OS you use? Problem with `require_patch` appear only on Windows or in case of old version of Ruby. So, please, provide me more information about installation. And anyway, most likely you have problem with environment of installation, not with plugin.

**Comment by walkwolf** [comment]
I find bitnami private directory  ```/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle```
So I do this:
``` bundle install --path /home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle```
Then restart apache2.
But it still not work,
I can find error in apache error log file:
```
 Message from application: undefined method `require_patch' for #<ActionDispatch::Reloader:0x007fad4b3d8ce0> (NoMethodError)
  /home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/plugins/redmine_issues_tree/init.rb:15:in `block in <top (required)>'
```

OS :CentOS release 6.4 (Final)

```
bash-4.1$ which rake
/home/redmine/redmine-3.2.0-0/ruby/bin/rake
bash-4.1$ which gem
/home/redmine/redmine-3.2.0-0/ruby/bin/gem
bash-4.1$ gem -v
2.0.14.1
bash-4.1$ rake --version
rake, version 10.5.0
bash-4.1$ bundle --version
Bundler version 1.10.4

```
gem list -l
```
bash-4.1$ gem list -l

*** LOCAL GEMS ***

actionmailer (4.2.4)
actionpack (4.2.5, 4.2.4)
actionview (4.2.5, 4.2.4)
activejob (4.2.4)
activemodel (4.2.4)
activerecord (4.2.4)
activesupport (4.2.5, 4.2.4)
akami (1.2.0)
arel (6.0.3)
atomic (1.1.14)
aws-sdk (2.1.1)
aws-sdk-core (2.1.1)
aws-sdk-resources (2.1.1)
bcrypt-ruby (3.1.1)
bigdecimal (1.2.0)
binding_of_caller (0.7.2)
bluecloth (2.2.0)
builder (3.2.2)
bundler (1.10.4)
byebug (3.5.1)
charlock_holmes (0.6.9.4)
coffee-rails (4.1.0)
coffee-script (2.2.0)
coffee-script-source (1.6.2)
columnize (0.9.0)
crack (0.3.1)
daemon_controller (1.2.0)
daemons (1.1.8)
debug_inspector (0.0.2)
debugger-linecache (1.2.0)
diff-lcs (1.1.3)
erubis (2.7.0)
escape_utils (0.2.4)
eventmachine (1.0.4)
execjs (1.4.0)
faraday (0.8.4)
faraday_middleware (0.9.0)
fast_stack (0.1.0)
fast_xor (1.1.1)
fast_xs (0.8.0)
ffi (1.9.0)
gherkin (2.11.1)
github-markdown (0.5.3)
globalid (0.3.6)
gyoku (0.4.6)
haml (4.0.7)
haml-rails (0.9.0)
hashie (1.2.0)
hike (1.2.3)
hiredis (0.4.5)
hoe (3.0.6)
hoe-bundler (1.2.0)
hoe-debugging (1.0.5)
hoe-gemspec (1.0.0)
html2haml (2.0.0)
http_parser.rb (0.5.3)
httparty (0.8.3)
httpauth (0.2.0)
i18n (0.7.0)
iconv (1.0.3)
io-console (0.4.2)
jbuilder (2.0.7)
jmespath (1.0.2)
jquery-rails (3.0.4)
json (1.8.3, 1.7.7)
jwt (0.1.8)
libv8 (3.16.14.3 x86_64-linux)
loofah (2.0.3)
mail (2.6.3)
memcache-client (1.8.5)
mime-types (2.6.2)
mini_magick (3.4)
mini_portile (0.6.0)
mini_portile2 (2.0.0)
minitest (5.8.3, 5.8.1, 4.3.2, 3.3.0)
multi_json (1.5.0, 1.3.6)
multi_xml (0.5.1)
multipart-post (1.1.5)
mysql2 (0.3.14)
nokogiri (1.6.7.1, 1.6.2.1, 1.5.9)
oauth (0.4.7)
oj (2.0.11)
omniauth (1.1.4)
passenger (5.0.6)
pg (0.18.0.pre20141117110243, 0.15.1)
polyglot (0.3.3)
posix-spawn (0.3.6)
psych (2.0.0)
racc (1.4.8)
rack (1.6.4)
rack-test (0.6.3)
rails (4.2.4)
rails-deprecated_sanitizer (1.0.3)
rails-dom-testing (1.0.7)
rails-html-sanitizer (1.0.2)
railties (4.2.5, 4.2.4)
rake (10.5.0, 10.4.2, 0.9.6, 0.8.7)
rake-compiler (0.8.1)
rdiscount (1.6.8)
rdoc (4.0.0)
redcarpet (3.0.0, 2.2.2)
RedCloth (4.2.9)
redis (3.0.4)
ref (1.0.2)
require_patch (0.1.0)
rexical (1.0.5)
rinku (1.7.3)
rmagick (2.13.1)
rspec (2.11.0)
rspec-core (2.11.1)
rspec-expectations (2.11.2)
rspec-mocks (2.11.1)
ruby-hmac (0.4.0)
ruby_parser (3.7.2)
rvm (1.11.3.5)
sass (3.4.14)
sass-rails (5.0.3)
sdoc (0.4.0)
sexp_processor (4.6.0)
simple_oauth (0.1.9)
slop (3.6.0)
spring (1.2.0)
sprockets (3.4.0, 2.2.1)
sprockets-rails (2.3.3)
sqlite3 (1.3.10)
sqlite3-ruby (1.3.3)
subexec (0.2.2)
test-unit (2.0.0.0)
therubyracer (0.12.0)
thin (1.5.1)
thor (0.19.1, 0.18.1)
thread_safe (0.3.5)
tilt (2.0.2, 1.4.1)
treetop (1.4.14)
turbolinks (1.2.0)
twitter-stream (0.1.16)
tzinfo (1.2.2)
tzinfo-data (1.2014.2)
uglifier (2.1.1)
uuidtools (2.1.3)
web-console (2.0.0)
yajl-ruby (1.1.0)
```
bundle list
```
bash-4.1$ bundle list
Gems included by the bundle:
  * actionmailer (4.2.5)
  * actionpack (4.2.5)
  * actionpack-action_caching (1.1.1)
  * actionpack-xml_parser (1.0.2)
  * actionview (4.2.5)
  * activejob (4.2.5)
  * activemodel (4.2.5)
  * activerecord (4.2.5)
  * activesupport (4.2.5)
  * addressable (2.4.0)
  * arel (6.0.3)
  * builder (3.2.2)
  * bundler (1.10.4)
  * coderay (1.1.0)
  * concurrent-ruby (1.0.0)
  * css_parser (1.3.7)
  * erubis (2.7.0)
  * globalid (0.3.6)
  * htmlentities (4.3.1)
  * i18n (0.7.0)
  * jquery-rails (3.1.4)
  * json (1.8.3)
  * loofah (2.0.3)
  * mail (2.6.3)
  * mime-types (2.99)
  * mini_portile2 (2.0.0)
  * minitest (5.8.3)
  * mysql2 (0.3.14)
  * net-ldap (0.12.1)
  * nokogiri (1.6.7)
  * protected_attributes (1.1.3)
  * rack (1.6.4)
  * rack-openid (1.4.2)
  * rack-test (0.6.3)
  * rails (4.2.5)
  * rails-deprecated_sanitizer (1.0.3)
  * rails-dom-testing (1.0.7)
  * rails-html-sanitizer (1.0.2)
  * railties (4.2.5)
  * rake (10.4.2)
  * rbpdf (1.19.0)
  * rbpdf-font (1.19.0)
  * redcarpet (3.3.3)
  * request_store (1.0.5)
  * rmagick (2.15.4)
  * roadie (3.1.0)
  * roadie-rails (1.1.0)
  * ruby-openid (2.3.0)
  * sprockets (3.5.1)
  * sprockets-rails (2.3.3)
  * thor (0.19.1)
  * thread_safe (0.3.5)
  * tzinfo (1.2.2)
bash-4.1$ 
```

**Comment by walkwolf** [comment]
Thanks Loriowar.
Ha. I resolve this problem.
I find below from ```https://wiki.bitnami.com/Applications/BitNami_Redmine#How_to_install_a_plugin_on_Redmine.3f``` 
```
$ cd installdir
$ ./use_redmine
$ cd apps/redmine/htdocs
$ bundle install --without development test postgresql sqlite --no-deployment
$ bundle install --without development test postgresql sqlite --deployment
$ ruby bin/rake redmine:plugins RAILS_ENV=production
```
Default use the bitnami ./use_redmine ,then ```bundle install --without development test postgresql sqlite --deployment``` while gem install on the ```/home/redmine/redmine-3.2.0-0/ruby/lib/ruby/gems/2.0.0/gems```
And ```deployment``` while copy this installed to ```/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems```

Then run ```ruby bin/rake redmine:plugins RAILS_ENV=production```
It's work!!!

But I find a problem,maybe not.
It's require nokogiri ,so ``` yum install libxml2 libxml2-devel``` .
And while bundle proceed, it's prompt message 
```
Fetching gem metadata from https://ruby.taobao.org/...........
Fetching version metadata from https://ruby.taobao.org/..
Resolving dependencies...
Could not find rbpdf-font-1.19.0 in any of the sources
```
I modify redmine_issues_tree/Gemfile ,add ```gem 'rbpdf-font', '~> 1.19.0'``` first line.

Anyway ,it's work now .
Good plugin ,thinks Loriowar.

**Comment by Loriowar** [comment]
Glad for you. Good luck!
