### ISSUE TITLE
not working with redmine 4.0.1

### ISSUE THREAD

**Issue by SandraK82** [Loriowar/redmine_issues_tree#87]
bundle exec rake redmine:plugins RAILS_ENV=production
rake aborted!
NoMethodError: undefined method `alias_method_chain' for IssuesController:Class
Did you mean?  alias_method
/var/www/redmine/redmine-4.0.1/plugins/redmine_issues_tree/lib/redmine_issues_tree/issues_controller_patch.rb:5:in `block in <module:IssuesControllerPatch>'
/usr/share/rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/concern.rb:122:in `class_eval'
/usr/share/rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/concern.rb:122:in `append_features'
/usr/share/rvm/gems/ruby-2.5.0/gems/require_patch-0.3.3/lib/require_patch.rb:30:in `include'
/usr/share/rvm/gems/ruby-2.5.0/gems/require_patch-0.3.3/lib/require_patch.rb:30:in `block in require_patch'
/usr/share/rvm/gems/ruby-2.5.0/gems/require_patch-0.3.3/lib/require_patch.rb:23:in `each'
/usr/share/rvm/gems/ruby-2.5.0/gems/require_patch-0.3.3/lib/require_patch.rb:23:in `require_patch'
/var/www/redmine/redmine-4.0.1/plugins/redmine_issues_tree/init.rb:17:in `block in <top (required)>'
/usr/share/rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:426:in `instance_exec'
/usr/share/rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:426:in `block in make_lambda'
/usr/share/rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
/usr/share/rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
/usr/share/rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:605:in `catch'
/usr/share/rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:605:in `block in default_terminator'
/usr/share/rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:199:in `block in halting'
/usr/share/rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:513:in `block in invoke_before'
/usr/share/rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:513:in `each'
/usr/share/rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:513:in `invoke_before'
/usr/share/rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:131:in `run_callbacks'
/usr/share/rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/reloader.rb:89:in `prepare!'
/usr/share/rvm/gems/ruby-2.5.0/gems/railties-5.2.2/lib/rails/application/finisher.rb:63:in `block in <module:Finisher>'
/usr/share/rvm/gems/ruby-2.5.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `instance_exec'
/usr/share/rvm/gems/ruby-2.5.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `run'
/usr/share/rvm/gems/ruby-2.5.0/gems/railties-5.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/share/rvm/gems/ruby-2.5.0/gems/railties-5.2.2/lib/rails/initializable.rb:60:in `run_initializers'
/usr/share/rvm/gems/ruby-2.5.0/gems/railties-5.2.2/lib/rails/application.rb:361:in `initialize!'
/var/www/redmine/redmine-4.0.1/config/environment.rb:14:in `<top (required)>'
/usr/share/rvm/gems/ruby-2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/share/rvm/gems/ruby-2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/share/rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
/usr/share/rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/share/rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
/usr/share/rvm/gems/ruby-2.5.0/gems/railties-5.2.2/lib/rails/application.rb:337:in `require_environment!'
/usr/share/rvm/gems/ruby-2.5.0/gems/railties-5.2.2/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/var/www/redmine/redmine-4.0.1/lib/tasks/redmine.rake:57:in `block (2 levels) in <top (required)>'
/usr/share/rvm/gems/ruby-2.5.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/usr/share/rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:24:in `eval'
/usr/share/rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment

**Comment by Loriowar** [comment]
Most likely, you use a wrong branch of the plugin. Please, switch to branch `4.0.x`. Only this one working properly with Redmine 4.0.1.

**Comment by Loriowar** [comment]
Looks like problem is solved.
