### ISSUE TITLE
undefined method `allowed_target_trackers' for #<Class:0x00000003b354b8> Did you mean?  allowed_target_projects

### ISSUE THREAD

**Issue by gargtushar** [Loriowar/redmine_issues_tree#43]
I also installed a_common_libs plugin to redmine but I am getting the same issue

**Comment by gargtushar** [comment]
ActionView::Template::Error (undefined method `allowed_target_trackers' for #<Class:0x00000003b354b8>
Did you mean?  allowed_target_projects):
    3: <%# end patch %>
    4: 
    5: <div class="contextual">
    6:   <% if User.current.allowed_to?(:add_issues, @project, :global => true) && (@project.nil? || Issue.allowed_target_trackers(@project).any?) %>
    7:     <%= link_to l(:label_issue_new), _new_project_issue_path(@project), :class => 'icon icon-add new-issue' %>
    8:   <% end %>
    9: 
  app/controllers/issues_controller.rb:142:in `block (2 levels) in index'
  app/controllers/issues_controller.rb:141:in `index'


  Rendered /home/daffodil-53/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/templates/rescues/_source.erb (5.2ms)
  Rendered /home/daffodil-53/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.9ms)
  Rendered /home/daffodil-53/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.1ms)
  Rendered /home/daffodil-53/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/templates/rescues/template_error.html.erb within rescues/layout (21.7ms)

**Comment by Loriowar** [comment]
Look at [Redmine page of the plugin](https://www.redmine.org/plugins/redmine_issues_tree#Compatibility-issues). Redmine_issue_tree is incompatible with a_common_libs. So, select only one of these plugins.

**Comment by gargtushar** [comment]
ok

**Comment by gargtushar** [comment]
after uninstalling a_common_libs plugin, I got the same error

**Comment by Loriowar** [comment]
Sounds strange. Here is several variants: you miss restart of web-server after removing plugin; you have other redefinitions of issues partials and/or templates in other installed plugins.

On pure Redmine all works right. Problem may appear only in case of redefinition of `isses/index` template or in case of changes in logic of working with issues.

**Comment by gargtushar** [comment]
I am using Redmine Agile Plugin, and also restart the web server and getting the same error

**Comment by gargtushar** [comment]
and I am not able to get the definition of allowed_target_trackers in my whole project

**Comment by gargtushar** [comment]
There is no change in the logic of issues working, it's same like pure redmine

**Comment by Jiangshan00001** [comment]
i have the same problem:
the plugin i used is:
Redmine3.2.1
easy_gantt, easy_wbs, gantt_on_issue_tree, projects_treeview, redmine_dashboard, redmine_spent_time,redmine_task_board, redmine_timebank, redmine_work_time,time_logger.

they works fine in Redmine3.3.1. but for some reason I have to goto 3.2.1 and the problem happens.



  Rendered plugins/redmine_issues_tree/app/views/issues_trees/_issues_index_header_tags.html.haml (2.5ms)
  Rendered plugins/redmine_issues_tree/app/views/issues/index.html.erb within layouts/base (54.6ms)
Completed 500 Internal Server Error in 289ms (ActiveRecord: 169.7ms)

ActionView::Template::Error (undefined method `allowed_target_trackers' for #<Class:0x00000003164650>
Did you mean?  allowed_target_projects):
    3: <%# end patch %>
    4:
    5: <div class="contextual">
    6:   <% if User.current.allowed_to?(:add_issues, @project, :global => true) && (@project.nil? || Issue.allowed_target_trackers(@p                    roject).any?) %>
    7:     <%= link_to l(:label_issue_new), _new_project_issue_path(@project), :class => 'icon icon-add new-issue' %>
    8:   <% end %>
    9:
  plugins/redmine_issues_tree/app/views/issues/index.html.erb:6:in `_plugins_redmine_issues_tree_app_views_issues_index_html_erb__194                    7357180555663837_70066004812860'
  app/controllers/issues_controller.rb:77:in `block (2 levels) in index'
  app/controllers/issues_controller.rb:76:in `index'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by Jiangshan00001** [comment]
I tried Redmine 3.2.1.stable, with just one plugin: redmine_issues_tree. it do not work.
other plugin is uninstalled as the redmine.org said.
am I anything wrong?

**Comment by Loriowar** [comment]
You use branch `3.3.x` within Redmine 3.2. This is a source of your problem. Please, use plugin branch corresponding to your Redmine version.

**Comment by gargtushar** [comment]
@Jiangshan00001 , just create your own, I have faced the same issues as you are facing, in that case I created my own, but sorry to say can't share, becoz it is in development right now.

**Comment by Jiangshan00001** [comment]
@gargtushar thanks. I used another one: https://github.com/charleneChen/redmine_issues_tree_view
it works for me. 
thanks.
